version: '3.9'

services:
  frontend:
    build:
      context: ./boxure-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./boxure-frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./boxure-services
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./boxure-services:/app
      - backend_node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./boxure-services/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  frontend_node_modules:
  backend_node_modules:
  postgres_data:
